server:
  port: 8080
  servlet:
    context-path: /api/v1/api-ecommerce/

spring:
  datasource:
    url: ${ DATASOURCE }
    driver-class-name: org.postgresql.Driver
    username: ${ USERNAME }
    password: ${ PASSWORD }
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect