name: üöÄ CI/CD - Deploy Java Service to VPS

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: üì¶ Checkout code
        uses: actions/checkout@v4

      - name: ‚òï Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: üèóÔ∏è Build JAR
        run: mvn clean package -DskipTests

      - name: üîë Connect to VPS & Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY}}
          script: |
            echo "üì¶ Desplegando proyecto en VPS..."
            mkdir -p /home/${{ secrets.DEPLOY_USER }}/proyectos/api-ecommerce
            pkill -f 'mi-proyecto-0.0.1-SNAPSHOT.jar' || true
            rm -f /home/${{ secrets.DEPLOY_USER }}/proyectos/api-ecommerce/*.jar
            exit

      - name: üì§ Upload JAR to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "target/mi-proyecto-0.0.1-SNAPSHOT.jar"
          target: "/home/${{ secrets.DEPLOY_USER }}/proyectos/mi-proyecto/"

      - name: üöÄ Run service on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/${{ secrets.DEPLOY_USER }}/proyectos/mi-proyecto
            nohup java -jar mi-proyecto-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            echo "‚úÖ Aplicaci√≥n ejecut√°ndose"
